#server:
#  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist_db
    username: todolist
    password: todolist
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true